# Generated by Django 2.2.18 on 2024-12-22 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundCloud',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_soundcloud_soundcloud', serialize=False, to='cms.CMSPlugin')),
                ('url', models.CharField(help_text='(i. e. https://soundcloud.com/band/song)', max_length=255, verbose_name='Sound Cloud URL')),
                ('author_name', models.CharField(editable=False, max_length=255)),
                ('author_url', models.CharField(editable=False, max_length=255)),
                ('title', models.CharField(editable=False, max_length=255)),
                ('description', models.CharField(editable=False, max_length=255)),
                ('thumbnail_url', models.CharField(editable=False, max_length=255)),
                ('color', models.CharField(choices=[('ff6600', 'Default')], default='ff6600', help_text='Main color of the widget.', max_length=6, verbose_name='Color')),
                ('auto_play', models.BooleanField(verbose_name='Play automatically')),
                ('show_artwork', models.BooleanField(verbose_name='Show artwork')),
                ('hide_related', models.BooleanField(verbose_name='Hide related')),
                ('visual', models.BooleanField(verbose_name='Visual mode')),
                ('height', models.IntegerField(choices=[(300, 300), (450, 450), (600, 600)], default=300, help_text='Height of widhte in visual mode.', verbose_name='Height')),
                ('src', models.TextField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
